package com.nf147.ssm.dao;

import com.nf147.ssm.entity.Education;
import java.util.List;

public interface EducationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer educationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbg.generated
     */
    int insert(Education record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbg.generated
     */
    Education selectByPrimaryKey(Integer educationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbg.generated
     */
    List<Education> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table education
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Education record);
}