package com.nf147.ssm.entity;

import java.math.BigDecimal;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_id
     *
     * @mbg.generated
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_num
     *
     * @mbg.generated
     */
    private String employeeNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_name
     *
     * @mbg.generated
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_sex
     *
     * @mbg.generated
     */
    private Integer employeeSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.education_id
     *
     * @mbg.generated
     */
    private Integer educationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.employee_price
     *
     * @mbg.generated
     */
    private double employeePrice;

    private Education education;

    public Education getEducation() {
        return education;
    }

    public void setEducation(Education education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_id
     *
     * @return the value of employee.employee_id
     *
     * @mbg.generated
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_id
     *
     * @param employeeId the value for employee.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_num
     *
     * @return the value of employee.employee_num
     *
     * @mbg.generated
     */
    public String getEmployeeNum() {
        return employeeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_num
     *
     * @param employeeNum the value for employee.employee_num
     *
     * @mbg.generated
     */
    public void setEmployeeNum(String employeeNum) {
        this.employeeNum = employeeNum == null ? null : employeeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_name
     *
     * @return the value of employee.employee_name
     *
     * @mbg.generated
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_name
     *
     * @param employeeName the value for employee.employee_name
     *
     * @mbg.generated
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.employee_sex
     *
     * @return the value of employee.employee_sex
     *
     * @mbg.generated
     */
    public Integer getEmployeeSex() {
        return employeeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.employee_sex
     *
     * @param employeeSex the value for employee.employee_sex
     *
     * @mbg.generated
     */
    public void setEmployeeSex(Integer employeeSex) {
        this.employeeSex = employeeSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.education_id
     *
     * @return the value of employee.education_id
     *
     * @mbg.generated
     */
    public Integer getEducationId() {
        return educationId;
    }

    public double getEmployeePrice() {
        return employeePrice;
    }

    public void setEmployeePrice(double employeePrice) {
        this.employeePrice = employeePrice;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "employeeId=" + employeeId +
                ", employeeNum='" + employeeNum + '\'' +
                ", employeeName='" + employeeName + '\'' +
                ", employeeSex=" + employeeSex +
                ", educationId=" + educationId +
                ", employeePrice=" + employeePrice +
                ", education=" + education +
                '}';
    }
}